/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: correctwrap.i

package correctwrap

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



#cgo LDFLAGS: -lcorrect

typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef long long swig_type_5;
typedef long long swig_type_6;
typedef long long swig_type_7;
typedef long long swig_type_8;
typedef long long swig_type_9;
typedef long long swig_type_10;
typedef long long swig_type_11;
typedef long long swig_type_12;
typedef long long swig_type_13;
extern void _wrap_Swig_free_correctwrap_e4919b786a50effe(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_correctwrap_e4919b786a50effe(swig_intgo arg1);
extern swig_voidp _wrap_correct_conv_r12_6_polynomial_get_correctwrap_e4919b786a50effe(void);
extern swig_voidp _wrap_correct_conv_r12_7_polynomial_get_correctwrap_e4919b786a50effe(void);
extern swig_voidp _wrap_correct_conv_r12_8_polynomial_get_correctwrap_e4919b786a50effe(void);
extern swig_voidp _wrap_correct_conv_r12_9_polynomial_get_correctwrap_e4919b786a50effe(void);
extern swig_voidp _wrap_correct_conv_r13_6_polynomial_get_correctwrap_e4919b786a50effe(void);
extern swig_voidp _wrap_correct_conv_r13_7_polynomial_get_correctwrap_e4919b786a50effe(void);
extern swig_voidp _wrap_correct_conv_r13_8_polynomial_get_correctwrap_e4919b786a50effe(void);
extern swig_voidp _wrap_correct_conv_r13_9_polynomial_get_correctwrap_e4919b786a50effe(void);
extern uintptr_t _wrap_correct_convolutional_create_correctwrap_e4919b786a50effe(swig_type_1 arg1, swig_type_2 arg2, swig_voidp arg3);
extern void _wrap_correct_convolutional_destroy_correctwrap_e4919b786a50effe(uintptr_t arg1);
extern swig_type_3 _wrap_correct_convolutional_encode_len_correctwrap_e4919b786a50effe(uintptr_t arg1, swig_type_4 arg2);
extern swig_type_5 _wrap_correct_convolutional_encode_correctwrap_e4919b786a50effe(uintptr_t arg1, swig_voidp arg2, swig_type_6 arg3, swig_voidp arg4);
extern uintptr_t _wrap_correct_convolutional_decode_correctwrap_e4919b786a50effe(uintptr_t arg1, swig_voidp arg2, swig_type_7 arg3, swig_voidp arg4);
extern uintptr_t _wrap_correct_convolutional_decode_soft_correctwrap_e4919b786a50effe(uintptr_t arg1, swig_voidp arg2, swig_type_8 arg3, swig_voidp arg4);
extern short _wrap_correct_rs_primitive_polynomial_8_4_3_2_0_get_correctwrap_e4919b786a50effe(void);
extern short _wrap_correct_rs_primitive_polynomial_8_5_3_1_0_get_correctwrap_e4919b786a50effe(void);
extern short _wrap_correct_rs_primitive_polynomial_8_5_3_2_0_get_correctwrap_e4919b786a50effe(void);
extern short _wrap_correct_rs_primitive_polynomial_8_6_3_2_0_get_correctwrap_e4919b786a50effe(void);
extern short _wrap_correct_rs_primitive_polynomial_8_6_4_3_2_1_0_get_correctwrap_e4919b786a50effe(void);
extern short _wrap_correct_rs_primitive_polynomial_8_6_5_1_0_get_correctwrap_e4919b786a50effe(void);
extern short _wrap_correct_rs_primitive_polynomial_8_6_5_2_0_get_correctwrap_e4919b786a50effe(void);
extern short _wrap_correct_rs_primitive_polynomial_8_6_5_3_0_get_correctwrap_e4919b786a50effe(void);
extern short _wrap_correct_rs_primitive_polynomial_8_6_5_4_0_get_correctwrap_e4919b786a50effe(void);
extern short _wrap_correct_rs_primitive_polynomial_8_7_2_1_0_get_correctwrap_e4919b786a50effe(void);
extern short _wrap_correct_rs_primitive_polynomial_8_7_3_2_0_get_correctwrap_e4919b786a50effe(void);
extern short _wrap_correct_rs_primitive_polynomial_8_7_5_3_0_get_correctwrap_e4919b786a50effe(void);
extern short _wrap_correct_rs_primitive_polynomial_8_7_6_1_0_get_correctwrap_e4919b786a50effe(void);
extern short _wrap_correct_rs_primitive_polynomial_8_7_6_3_2_1_0_get_correctwrap_e4919b786a50effe(void);
extern short _wrap_correct_rs_primitive_polynomial_8_7_6_5_2_1_0_get_correctwrap_e4919b786a50effe(void);
extern short _wrap_correct_rs_primitive_polynomial_8_7_6_5_4_2_0_get_correctwrap_e4919b786a50effe(void);
extern short _wrap_correct_rs_primitive_polynomial_ccsds_get_correctwrap_e4919b786a50effe(void);
extern uintptr_t _wrap_correct_reed_solomon_create_correctwrap_e4919b786a50effe(short arg1, char arg2, char arg3, swig_type_9 arg4);
extern uintptr_t _wrap_correct_reed_solomon_encode_correctwrap_e4919b786a50effe(uintptr_t arg1, swig_voidp arg2, swig_type_10 arg3, swig_voidp arg4);
extern uintptr_t _wrap_correct_reed_solomon_decode_correctwrap_e4919b786a50effe(uintptr_t arg1, swig_voidp arg2, swig_type_11 arg3, swig_voidp arg4);
extern uintptr_t _wrap_correct_reed_solomon_decode_with_erasures_correctwrap_e4919b786a50effe(uintptr_t arg1, swig_voidp arg2, swig_type_12 arg3, swig_voidp arg4, swig_type_13 arg5, swig_voidp arg6);
extern void _wrap_correct_reed_solomon_destroy_correctwrap_e4919b786a50effe(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"

type _ unsafe.Pointer

var Swig_escape_always_false bool
var Swig_escape_val interface{}

type _swig_fnptr *byte
type _swig_memberptr *byte

type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_correctwrap_e4919b786a50effe(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_correctwrap_e4919b786a50effe(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func GetCorrect_conv_r12_6_polynomial() (_swig_ret *uint16) {
	var swig_r *uint16
	swig_r = (*uint16)(C._wrap_correct_conv_r12_6_polynomial_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_conv_r12_7_polynomial() (_swig_ret *uint16) {
	var swig_r *uint16
	swig_r = (*uint16)(C._wrap_correct_conv_r12_7_polynomial_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_conv_r12_8_polynomial() (_swig_ret *uint16) {
	var swig_r *uint16
	swig_r = (*uint16)(C._wrap_correct_conv_r12_8_polynomial_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_conv_r12_9_polynomial() (_swig_ret *uint16) {
	var swig_r *uint16
	swig_r = (*uint16)(C._wrap_correct_conv_r12_9_polynomial_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_conv_r13_6_polynomial() (_swig_ret *uint16) {
	var swig_r *uint16
	swig_r = (*uint16)(C._wrap_correct_conv_r13_6_polynomial_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_conv_r13_7_polynomial() (_swig_ret *uint16) {
	var swig_r *uint16
	swig_r = (*uint16)(C._wrap_correct_conv_r13_7_polynomial_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_conv_r13_8_polynomial() (_swig_ret *uint16) {
	var swig_r *uint16
	swig_r = (*uint16)(C._wrap_correct_conv_r13_8_polynomial_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_conv_r13_9_polynomial() (_swig_ret *uint16) {
	var swig_r *uint16
	swig_r = (*uint16)(C._wrap_correct_conv_r13_9_polynomial_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func Correct_convolutional_create(arg1 int64, arg2 int64, arg3 *uint16) (_swig_ret Correct_convolutional) {
	var swig_r Correct_convolutional
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Correct_convolutional)(SwigcptrCorrect_convolutional(C._wrap_correct_convolutional_create_correctwrap_e4919b786a50effe(C.swig_type_1(_swig_i_0), C.swig_type_2(_swig_i_1), C.swig_voidp(_swig_i_2))))
	return swig_r
}

func Correct_convolutional_destroy(arg1 Correct_convolutional) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_correct_convolutional_destroy_correctwrap_e4919b786a50effe(C.uintptr_t(_swig_i_0))
}

func Correct_convolutional_encode_len(arg1 Correct_convolutional, arg2 int64) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int64)(C._wrap_correct_convolutional_encode_len_correctwrap_e4919b786a50effe(C.uintptr_t(_swig_i_0), C.swig_type_4(_swig_i_1)))
	return swig_r
}

func Correct_convolutional_encode(arg1 Correct_convolutional, arg2 *byte, arg3 int64, arg4 *byte) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int64)(C._wrap_correct_convolutional_encode_correctwrap_e4919b786a50effe(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_type_6(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func Correct_convolutional_decode(arg1 Correct_convolutional, arg2 *byte, arg3 int64, arg4 *byte) (_swig_ret Ssize_t) {
	var swig_r Ssize_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (Ssize_t)(SwigcptrSsize_t(C._wrap_correct_convolutional_decode_correctwrap_e4919b786a50effe(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_type_7(_swig_i_2), C.swig_voidp(_swig_i_3))))
	return swig_r
}

func Correct_convolutional_decode_soft(arg1 Correct_convolutional, arg2 *byte, arg3 int64, arg4 *byte) (_swig_ret Ssize_t) {
	var swig_r Ssize_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (Ssize_t)(SwigcptrSsize_t(C._wrap_correct_convolutional_decode_soft_correctwrap_e4919b786a50effe(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_type_8(_swig_i_2), C.swig_voidp(_swig_i_3))))
	return swig_r
}

func GetCorrect_rs_primitive_polynomial_8_4_3_2_0() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_correct_rs_primitive_polynomial_8_4_3_2_0_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_rs_primitive_polynomial_8_5_3_1_0() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_correct_rs_primitive_polynomial_8_5_3_1_0_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_rs_primitive_polynomial_8_5_3_2_0() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_correct_rs_primitive_polynomial_8_5_3_2_0_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_rs_primitive_polynomial_8_6_3_2_0() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_correct_rs_primitive_polynomial_8_6_3_2_0_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_rs_primitive_polynomial_8_6_4_3_2_1_0() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_correct_rs_primitive_polynomial_8_6_4_3_2_1_0_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_rs_primitive_polynomial_8_6_5_1_0() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_correct_rs_primitive_polynomial_8_6_5_1_0_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_rs_primitive_polynomial_8_6_5_2_0() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_correct_rs_primitive_polynomial_8_6_5_2_0_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_rs_primitive_polynomial_8_6_5_3_0() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_correct_rs_primitive_polynomial_8_6_5_3_0_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_rs_primitive_polynomial_8_6_5_4_0() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_correct_rs_primitive_polynomial_8_6_5_4_0_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_rs_primitive_polynomial_8_7_2_1_0() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_correct_rs_primitive_polynomial_8_7_2_1_0_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_rs_primitive_polynomial_8_7_3_2_0() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_correct_rs_primitive_polynomial_8_7_3_2_0_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_rs_primitive_polynomial_8_7_5_3_0() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_correct_rs_primitive_polynomial_8_7_5_3_0_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_rs_primitive_polynomial_8_7_6_1_0() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_correct_rs_primitive_polynomial_8_7_6_1_0_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_rs_primitive_polynomial_8_7_6_3_2_1_0() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_correct_rs_primitive_polynomial_8_7_6_3_2_1_0_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_rs_primitive_polynomial_8_7_6_5_2_1_0() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_correct_rs_primitive_polynomial_8_7_6_5_2_1_0_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_rs_primitive_polynomial_8_7_6_5_4_2_0() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_correct_rs_primitive_polynomial_8_7_6_5_4_2_0_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func GetCorrect_rs_primitive_polynomial_ccsds() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_correct_rs_primitive_polynomial_ccsds_get_correctwrap_e4919b786a50effe())
	return swig_r
}

func Correct_reed_solomon_create(arg1 uint16, arg2 byte, arg3 byte, arg4 int64) (_swig_ret Correct_reed_solomon) {
	var swig_r Correct_reed_solomon
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (Correct_reed_solomon)(SwigcptrCorrect_reed_solomon(C._wrap_correct_reed_solomon_create_correctwrap_e4919b786a50effe(C.short(_swig_i_0), C.char(_swig_i_1), C.char(_swig_i_2), C.swig_type_9(_swig_i_3))))
	return swig_r
}

func Correct_reed_solomon_encode(arg1 Correct_reed_solomon, arg2 *byte, arg3 int64, arg4 *byte) (_swig_ret Ssize_t) {
	var swig_r Ssize_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (Ssize_t)(SwigcptrSsize_t(C._wrap_correct_reed_solomon_encode_correctwrap_e4919b786a50effe(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_type_10(_swig_i_2), C.swig_voidp(_swig_i_3))))
	return swig_r
}

func Correct_reed_solomon_decode(arg1 Correct_reed_solomon, arg2 *byte, arg3 int64, arg4 *byte) (_swig_ret Ssize_t) {
	var swig_r Ssize_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (Ssize_t)(SwigcptrSsize_t(C._wrap_correct_reed_solomon_decode_correctwrap_e4919b786a50effe(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_type_11(_swig_i_2), C.swig_voidp(_swig_i_3))))
	return swig_r
}

func Correct_reed_solomon_decode_with_erasures(arg1 Correct_reed_solomon, arg2 *byte, arg3 int64, arg4 *byte, arg5 int64, arg6 *byte) (_swig_ret Ssize_t) {
	var swig_r Ssize_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (Ssize_t)(SwigcptrSsize_t(C._wrap_correct_reed_solomon_decode_with_erasures_correctwrap_e4919b786a50effe(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_type_12(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_type_13(_swig_i_4), C.swig_voidp(_swig_i_5))))
	return swig_r
}

func Correct_reed_solomon_destroy(arg1 Correct_reed_solomon) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_correct_reed_solomon_destroy_correctwrap_e4919b786a50effe(C.uintptr_t(_swig_i_0))
}

type SwigcptrCorrect_reed_solomon uintptr
type Correct_reed_solomon interface {
	Swigcptr() uintptr
}

func (p SwigcptrCorrect_reed_solomon) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrSsize_t uintptr
type Ssize_t interface {
	Swigcptr() uintptr
}

func (p SwigcptrSsize_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrCorrect_convolutional uintptr
type Correct_convolutional interface {
	Swigcptr() uintptr
}

func (p SwigcptrCorrect_convolutional) Swigcptr() uintptr {
	return uintptr(p)
}
