/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: correctwrap.i */

#define SWIGMODULE correctwrap
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include <stdint.h>		// Use the C99 official header


#include <correct.h>

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_correctwrap_e4919b786a50effe(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_correctwrap_e4919b786a50effe(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


short *_wrap_correct_conv_r12_6_polynomial_get_correctwrap_e4919b786a50effe() {
  correct_convolutional_polynomial_t *result = 0 ;
  short *_swig_go_result;
  
  
  result = (correct_convolutional_polynomial_t *)(correct_convolutional_polynomial_t *)correct_conv_r12_6_polynomial;
  *(correct_convolutional_polynomial_t **)&_swig_go_result = result; 
  return _swig_go_result;
}


short *_wrap_correct_conv_r12_7_polynomial_get_correctwrap_e4919b786a50effe() {
  correct_convolutional_polynomial_t *result = 0 ;
  short *_swig_go_result;
  
  
  result = (correct_convolutional_polynomial_t *)(correct_convolutional_polynomial_t *)correct_conv_r12_7_polynomial;
  *(correct_convolutional_polynomial_t **)&_swig_go_result = result; 
  return _swig_go_result;
}


short *_wrap_correct_conv_r12_8_polynomial_get_correctwrap_e4919b786a50effe() {
  correct_convolutional_polynomial_t *result = 0 ;
  short *_swig_go_result;
  
  
  result = (correct_convolutional_polynomial_t *)(correct_convolutional_polynomial_t *)correct_conv_r12_8_polynomial;
  *(correct_convolutional_polynomial_t **)&_swig_go_result = result; 
  return _swig_go_result;
}


short *_wrap_correct_conv_r12_9_polynomial_get_correctwrap_e4919b786a50effe() {
  correct_convolutional_polynomial_t *result = 0 ;
  short *_swig_go_result;
  
  
  result = (correct_convolutional_polynomial_t *)(correct_convolutional_polynomial_t *)correct_conv_r12_9_polynomial;
  *(correct_convolutional_polynomial_t **)&_swig_go_result = result; 
  return _swig_go_result;
}


short *_wrap_correct_conv_r13_6_polynomial_get_correctwrap_e4919b786a50effe() {
  correct_convolutional_polynomial_t *result = 0 ;
  short *_swig_go_result;
  
  
  result = (correct_convolutional_polynomial_t *)(correct_convolutional_polynomial_t *)correct_conv_r13_6_polynomial;
  *(correct_convolutional_polynomial_t **)&_swig_go_result = result; 
  return _swig_go_result;
}


short *_wrap_correct_conv_r13_7_polynomial_get_correctwrap_e4919b786a50effe() {
  correct_convolutional_polynomial_t *result = 0 ;
  short *_swig_go_result;
  
  
  result = (correct_convolutional_polynomial_t *)(correct_convolutional_polynomial_t *)correct_conv_r13_7_polynomial;
  *(correct_convolutional_polynomial_t **)&_swig_go_result = result; 
  return _swig_go_result;
}


short *_wrap_correct_conv_r13_8_polynomial_get_correctwrap_e4919b786a50effe() {
  correct_convolutional_polynomial_t *result = 0 ;
  short *_swig_go_result;
  
  
  result = (correct_convolutional_polynomial_t *)(correct_convolutional_polynomial_t *)correct_conv_r13_8_polynomial;
  *(correct_convolutional_polynomial_t **)&_swig_go_result = result; 
  return _swig_go_result;
}


short *_wrap_correct_conv_r13_9_polynomial_get_correctwrap_e4919b786a50effe() {
  correct_convolutional_polynomial_t *result = 0 ;
  short *_swig_go_result;
  
  
  result = (correct_convolutional_polynomial_t *)(correct_convolutional_polynomial_t *)correct_conv_r13_9_polynomial;
  *(correct_convolutional_polynomial_t **)&_swig_go_result = result; 
  return _swig_go_result;
}


correct_convolutional *_wrap_correct_convolutional_create_correctwrap_e4919b786a50effe(long long _swig_go_0, long long _swig_go_1, short *_swig_go_2) {
  size_t arg1 ;
  size_t arg2 ;
  correct_convolutional_polynomial_t *arg3 = (correct_convolutional_polynomial_t *) 0 ;
  correct_convolutional *result = 0 ;
  correct_convolutional *_swig_go_result;
  
  arg1 = (size_t)_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  arg3 = *(correct_convolutional_polynomial_t **)&_swig_go_2; 
  
  result = (correct_convolutional *)correct_convolutional_create(arg1,arg2,(unsigned short const *)arg3);
  *(correct_convolutional **)&_swig_go_result = (correct_convolutional *)result; 
  return _swig_go_result;
}


void _wrap_correct_convolutional_destroy_correctwrap_e4919b786a50effe(correct_convolutional *_swig_go_0) {
  correct_convolutional *arg1 = (correct_convolutional *) 0 ;
  
  arg1 = *(correct_convolutional **)&_swig_go_0; 
  
  correct_convolutional_destroy(arg1);
  
}


long long _wrap_correct_convolutional_encode_len_correctwrap_e4919b786a50effe(correct_convolutional *_swig_go_0, long long _swig_go_1) {
  correct_convolutional *arg1 = (correct_convolutional *) 0 ;
  size_t arg2 ;
  size_t result;
  long long _swig_go_result;
  
  arg1 = *(correct_convolutional **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  result = correct_convolutional_encode_len(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_correct_convolutional_encode_correctwrap_e4919b786a50effe(correct_convolutional *_swig_go_0, char *_swig_go_1, long long _swig_go_2, char *_swig_go_3) {
  correct_convolutional *arg1 = (correct_convolutional *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  size_t arg3 ;
  uint8_t *arg4 = (uint8_t *) 0 ;
  size_t result;
  long long _swig_go_result;
  
  arg1 = *(correct_convolutional **)&_swig_go_0; 
  arg2 = *(uint8_t **)&_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(uint8_t **)&_swig_go_3; 
  
  result = correct_convolutional_encode(arg1,(unsigned char const *)arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


ssize_t *_wrap_correct_convolutional_decode_correctwrap_e4919b786a50effe(correct_convolutional *_swig_go_0, char *_swig_go_1, long long _swig_go_2, char *_swig_go_3) {
  correct_convolutional *arg1 = (correct_convolutional *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  size_t arg3 ;
  uint8_t *arg4 = (uint8_t *) 0 ;
  ssize_t result;
  ssize_t *_swig_go_result;
  
  arg1 = *(correct_convolutional **)&_swig_go_0; 
  arg2 = *(uint8_t **)&_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(uint8_t **)&_swig_go_3; 
  
  result = correct_convolutional_decode(arg1,(unsigned char const *)arg2,arg3,arg4);
  {
    ssize_t * resultptr = (ssize_t *)malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


ssize_t *_wrap_correct_convolutional_decode_soft_correctwrap_e4919b786a50effe(correct_convolutional *_swig_go_0, char *_swig_go_1, long long _swig_go_2, char *_swig_go_3) {
  correct_convolutional *arg1 = (correct_convolutional *) 0 ;
  correct_convolutional_soft_t *arg2 = (correct_convolutional_soft_t *) 0 ;
  size_t arg3 ;
  uint8_t *arg4 = (uint8_t *) 0 ;
  ssize_t result;
  ssize_t *_swig_go_result;
  
  arg1 = *(correct_convolutional **)&_swig_go_0; 
  arg2 = *(correct_convolutional_soft_t **)&_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(uint8_t **)&_swig_go_3; 
  
  result = correct_convolutional_decode_soft(arg1,(unsigned char const *)arg2,arg3,arg4);
  {
    ssize_t * resultptr = (ssize_t *)malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


short _wrap_correct_rs_primitive_polynomial_8_4_3_2_0_get_correctwrap_e4919b786a50effe() {
  uint16_t result;
  short _swig_go_result;
  
  
  result = (uint16_t)(uint16_t)correct_rs_primitive_polynomial_8_4_3_2_0;
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_correct_rs_primitive_polynomial_8_5_3_1_0_get_correctwrap_e4919b786a50effe() {
  uint16_t result;
  short _swig_go_result;
  
  
  result = (uint16_t)(uint16_t)correct_rs_primitive_polynomial_8_5_3_1_0;
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_correct_rs_primitive_polynomial_8_5_3_2_0_get_correctwrap_e4919b786a50effe() {
  uint16_t result;
  short _swig_go_result;
  
  
  result = (uint16_t)(uint16_t)correct_rs_primitive_polynomial_8_5_3_2_0;
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_correct_rs_primitive_polynomial_8_6_3_2_0_get_correctwrap_e4919b786a50effe() {
  uint16_t result;
  short _swig_go_result;
  
  
  result = (uint16_t)(uint16_t)correct_rs_primitive_polynomial_8_6_3_2_0;
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_correct_rs_primitive_polynomial_8_6_4_3_2_1_0_get_correctwrap_e4919b786a50effe() {
  uint16_t result;
  short _swig_go_result;
  
  
  result = (uint16_t)(uint16_t)correct_rs_primitive_polynomial_8_6_4_3_2_1_0;
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_correct_rs_primitive_polynomial_8_6_5_1_0_get_correctwrap_e4919b786a50effe() {
  uint16_t result;
  short _swig_go_result;
  
  
  result = (uint16_t)(uint16_t)correct_rs_primitive_polynomial_8_6_5_1_0;
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_correct_rs_primitive_polynomial_8_6_5_2_0_get_correctwrap_e4919b786a50effe() {
  uint16_t result;
  short _swig_go_result;
  
  
  result = (uint16_t)(uint16_t)correct_rs_primitive_polynomial_8_6_5_2_0;
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_correct_rs_primitive_polynomial_8_6_5_3_0_get_correctwrap_e4919b786a50effe() {
  uint16_t result;
  short _swig_go_result;
  
  
  result = (uint16_t)(uint16_t)correct_rs_primitive_polynomial_8_6_5_3_0;
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_correct_rs_primitive_polynomial_8_6_5_4_0_get_correctwrap_e4919b786a50effe() {
  uint16_t result;
  short _swig_go_result;
  
  
  result = (uint16_t)(uint16_t)correct_rs_primitive_polynomial_8_6_5_4_0;
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_correct_rs_primitive_polynomial_8_7_2_1_0_get_correctwrap_e4919b786a50effe() {
  uint16_t result;
  short _swig_go_result;
  
  
  result = (uint16_t)(uint16_t)correct_rs_primitive_polynomial_8_7_2_1_0;
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_correct_rs_primitive_polynomial_8_7_3_2_0_get_correctwrap_e4919b786a50effe() {
  uint16_t result;
  short _swig_go_result;
  
  
  result = (uint16_t)(uint16_t)correct_rs_primitive_polynomial_8_7_3_2_0;
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_correct_rs_primitive_polynomial_8_7_5_3_0_get_correctwrap_e4919b786a50effe() {
  uint16_t result;
  short _swig_go_result;
  
  
  result = (uint16_t)(uint16_t)correct_rs_primitive_polynomial_8_7_5_3_0;
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_correct_rs_primitive_polynomial_8_7_6_1_0_get_correctwrap_e4919b786a50effe() {
  uint16_t result;
  short _swig_go_result;
  
  
  result = (uint16_t)(uint16_t)correct_rs_primitive_polynomial_8_7_6_1_0;
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_correct_rs_primitive_polynomial_8_7_6_3_2_1_0_get_correctwrap_e4919b786a50effe() {
  uint16_t result;
  short _swig_go_result;
  
  
  result = (uint16_t)(uint16_t)correct_rs_primitive_polynomial_8_7_6_3_2_1_0;
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_correct_rs_primitive_polynomial_8_7_6_5_2_1_0_get_correctwrap_e4919b786a50effe() {
  uint16_t result;
  short _swig_go_result;
  
  
  result = (uint16_t)(uint16_t)correct_rs_primitive_polynomial_8_7_6_5_2_1_0;
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_correct_rs_primitive_polynomial_8_7_6_5_4_2_0_get_correctwrap_e4919b786a50effe() {
  uint16_t result;
  short _swig_go_result;
  
  
  result = (uint16_t)(uint16_t)correct_rs_primitive_polynomial_8_7_6_5_4_2_0;
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_correct_rs_primitive_polynomial_ccsds_get_correctwrap_e4919b786a50effe() {
  uint16_t result;
  short _swig_go_result;
  
  
  result = (uint16_t)(uint16_t)correct_rs_primitive_polynomial_ccsds;
  _swig_go_result = result; 
  return _swig_go_result;
}


correct_reed_solomon *_wrap_correct_reed_solomon_create_correctwrap_e4919b786a50effe(short _swig_go_0, char _swig_go_1, char _swig_go_2, long long _swig_go_3) {
  uint16_t arg1 ;
  uint8_t arg2 ;
  uint8_t arg3 ;
  size_t arg4 ;
  correct_reed_solomon *result = 0 ;
  correct_reed_solomon *_swig_go_result;
  
  arg1 = (uint16_t)_swig_go_0; 
  arg2 = (uint8_t)_swig_go_1; 
  arg3 = (uint8_t)_swig_go_2; 
  arg4 = (size_t)_swig_go_3; 
  
  result = (correct_reed_solomon *)correct_reed_solomon_create(arg1,arg2,arg3,arg4);
  *(correct_reed_solomon **)&_swig_go_result = (correct_reed_solomon *)result; 
  return _swig_go_result;
}


ssize_t *_wrap_correct_reed_solomon_encode_correctwrap_e4919b786a50effe(correct_reed_solomon *_swig_go_0, char *_swig_go_1, long long _swig_go_2, char *_swig_go_3) {
  correct_reed_solomon *arg1 = (correct_reed_solomon *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  size_t arg3 ;
  uint8_t *arg4 = (uint8_t *) 0 ;
  ssize_t result;
  ssize_t *_swig_go_result;
  
  arg1 = *(correct_reed_solomon **)&_swig_go_0; 
  arg2 = *(uint8_t **)&_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(uint8_t **)&_swig_go_3; 
  
  result = correct_reed_solomon_encode(arg1,(unsigned char const *)arg2,arg3,arg4);
  {
    ssize_t * resultptr = (ssize_t *)malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


ssize_t *_wrap_correct_reed_solomon_decode_correctwrap_e4919b786a50effe(correct_reed_solomon *_swig_go_0, char *_swig_go_1, long long _swig_go_2, char *_swig_go_3) {
  correct_reed_solomon *arg1 = (correct_reed_solomon *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  size_t arg3 ;
  uint8_t *arg4 = (uint8_t *) 0 ;
  ssize_t result;
  ssize_t *_swig_go_result;
  
  arg1 = *(correct_reed_solomon **)&_swig_go_0; 
  arg2 = *(uint8_t **)&_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(uint8_t **)&_swig_go_3; 
  
  result = correct_reed_solomon_decode(arg1,(unsigned char const *)arg2,arg3,arg4);
  {
    ssize_t * resultptr = (ssize_t *)malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


ssize_t *_wrap_correct_reed_solomon_decode_with_erasures_correctwrap_e4919b786a50effe(correct_reed_solomon *_swig_go_0, char *_swig_go_1, long long _swig_go_2, char *_swig_go_3, long long _swig_go_4, char *_swig_go_5) {
  correct_reed_solomon *arg1 = (correct_reed_solomon *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  size_t arg3 ;
  uint8_t *arg4 = (uint8_t *) 0 ;
  size_t arg5 ;
  uint8_t *arg6 = (uint8_t *) 0 ;
  ssize_t result;
  ssize_t *_swig_go_result;
  
  arg1 = *(correct_reed_solomon **)&_swig_go_0; 
  arg2 = *(uint8_t **)&_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(uint8_t **)&_swig_go_3; 
  arg5 = (size_t)_swig_go_4; 
  arg6 = *(uint8_t **)&_swig_go_5; 
  
  result = correct_reed_solomon_decode_with_erasures(arg1,(unsigned char const *)arg2,arg3,(unsigned char const *)arg4,arg5,arg6);
  {
    ssize_t * resultptr = (ssize_t *)malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_correct_reed_solomon_destroy_correctwrap_e4919b786a50effe(correct_reed_solomon *_swig_go_0) {
  correct_reed_solomon *arg1 = (correct_reed_solomon *) 0 ;
  
  arg1 = *(correct_reed_solomon **)&_swig_go_0; 
  
  correct_reed_solomon_destroy(arg1);
  
}


#ifdef __cplusplus
}
#endif

